### PR TITLE
Add the Goose logo to the README

### PR DESCRIPTION
**Pull request by kitallis**
I've added the 2x version in the README and committed the 1x and 2x versions in the repo. The rest of the logos, including the original square ones and the [aseprite](https://www.aseprite.org) source files are in – [goose.art.zip](https://github.com/nilenso/goose/files/9333221/goose.art.zip).

I see some very solid progress in here. Good luck with the library!

P.S: Y'all should kick me off of the Github organization 🦀

### CODE REVIEW

**Comment by olttwa** [comment]
Hey @kitallis thanks a lot for this logo. I had 2 thoughts:

1. In the circular image, `blue` colour is filling a lot of space. Can we reduce the neck size a little more? That way, Goose will have more area I think
2. The `green` colours are very minuscule? Can we increase the grass a couple of millimetres from bottom? If we were to reduce the length of the neck, I think Goose will become centre and grass part will increase automatically.

Attaching a Goose image I took from Wikipedia for comparing bodily dimensions & link: https://en.wikipedia.org/wiki/Goose

Screenshot 2022-08-16 at 1 04 32 PM

**Comment by kitallis** [comment]
Thanks @olttwa. Let me give this a shot... next weekend.

1. The goose is centered based on the feet, not the body. It is a few pixels to the right, so that the beak wouldn't crash on the circle edge too close on the left. In other words, I've tried to keep the distance between the tail on the right edge the same as the distance between the beak and the left edge. I'll see if I can do anything about this. Not sure.
2. I kept the neck size longer, because this is a caricature of a goose, not an exact representation. Goose necks are typically exaggerated to be long and windy because they can extend them to be very long. I don't think I can reduce the neck size further because then it will feel disproportionate to the body.
3. I'll try increasing the green a bit more. Maybe wind behind the legs and feet a bit more.

**Comment by kitallis** [comment]
I should have some time tonight or tomorrow evening to wrap this up.

**Comment by kitallis** [comment]
I've increased the green a bit more and cut it a bit more proportionally across sizes. The uneven blue on either side is still there, can't really do much about that since the shape is oblong. Don't think I can do much more than this on a fundamentally rectangular artwork. 

[goose.art.zip](https://github.com/nilenso/goose/files/9459522/goose.art.zip)

Hope this helps!

**Pull request merged**
